# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# ===========================  wpc Configuration template for mwct2d17s, Revision: latest.  ============================

# ======================================================================================================================
#                                                 == General Options ==                                                 
# ======================================================================================================================
# -------------------------------------===== The chip family name [Required] =====--------------------------------------
# Description: NXP chip family identifier.
family: mwct2d17s
# -----------------------------------------===== MCU revision [Optional] =====------------------------------------------
# Description: Revision of silicon. The 'latest' name, means most current revision.
# Possible options: <a0, latest>
revision: latest
# --------------------------------===== Name of the WPC service adapter [Required] =====--------------------------------
# Description: Name of the WPC service adapter
# Possible options: <el2go, mywpc>
service_type: mywpc
# ----------------------------===== Parameters for the WPC service adapter [Required] =====-----------------------------
# Description: Parameters for the WPC service adapter
service_parameters:
  # -------------------------------------------===== Param1 [Required] =====--------------------------------------------
  # Description: Param1 for MyWPCService
  param1: something
  # -------------------------------------------===== Param2 [Required] =====--------------------------------------------
  # Description: Param2 for MyWPCService
  param2: 123
# ----------------------------------===== Name of the target adapter [Required] =====-----------------------------------
# Description: Name of the target adapter
# Possible options: <mboot, model>
target_type: model
# -------------------------------===== Parameters for the target adapter [Required] =====-------------------------------
# Description: Parameters for the target adapter
target_parameters:
  # ---------------------------------------===== Model directory [Required] =====---------------------------------------
  # Description: Path to directory containing the model (config.yaml)
  model_dir: <path/to/model_dir>
